import { Pool } from 'pg'
import { z } from 'zod'

export class DraftSaveError extends Error {
  constructor(
    public readonly code: 'ALREADY_SUBMITTED' | 'ENTITY_NOT_FOUND',
    message: string,
  ) {
    super(message)
    this.name = 'DraftSaveError'
  }
}

// Upserts a partial draft_data into revenue_day with status='DRAFT'.
// Stores the partial JSON loosely (no full DraftDataSchema validation here —
// that runs only at submit in T3d, since mid-wizard drafts lack financial data).
//
// Safety: the DO UPDATE WHERE clause prevents overwriting a SUBMITTED row.
// Returns { revenueDayId, isNew: true } on first insert, { revenueDayId, isNew: false } on update.
// Throws DraftSaveError('ALREADY_SUBMITTED') if the row exists but is not DRAFT.
export async function saveDraftDay(
  pool: Pool,
  actorId: string,
  entityId: string,
  date: string,
  partialDraft: unknown,
): Promise<{ revenueDayId: string; isNew: boolean }> {
  z.string().uuid('actorId must be a UUID').parse(actorId)
  z.string().uuid('entityId must be a UUID').parse(entityId)
  z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'date must be YYYY-MM-DD').parse(date)

  let rows: Array<{ id: string; is_new: boolean }>
  try {
    const result = await pool.query<{ id: string; is_new: boolean }>(
      `INSERT INTO public.revenue_day (entity_id, revenue_date, status, draft_data, created_by)
       VALUES ($1, $2, 'DRAFT', $3::jsonb, $4)
       ON CONFLICT (entity_id, revenue_date) DO UPDATE
         SET draft_data = EXCLUDED.draft_data,
             updated_by = $4
       WHERE public.revenue_day.status = 'DRAFT'
       RETURNING id, (xmax = 0) AS is_new`,
      [entityId, date, JSON.stringify(partialDraft), actorId],
    )
    rows = result.rows
  } catch (err) {
    // Catch FK violation on entity_id so raw Postgres errors never reach the client.
    // '23503' = foreign_key_violation; constraint name is auto-generated by Postgres.
    const pgErr = err as { code?: string; constraint?: string }
    if (pgErr.code === '23503' && pgErr.constraint === 'revenue_day_entity_id_fkey') {
      throw new DraftSaveError('ENTITY_NOT_FOUND', `entity ${entityId} not found`)
    }
    throw err
  }

  if (rows.length === 0) {
    throw new DraftSaveError('ALREADY_SUBMITTED', `${date} is already submitted — cannot overwrite`)
  }

  return { revenueDayId: rows[0].id, isNew: rows[0].is_new }
}
